name: RSS to Blogger AutoPoster

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

jobs:
  post_to_blogger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4

      - name: Install Dependencies
        run: pip install -r requirements.txt  # Only if a requirements.txt exists

      - name: Change to Repository Directory  # Fix to ensure correct directory
        run: cd ${{ github.workspace }}

      - name: Run RSS to Blogger Script
        env:
          BLOG_ID: ${{ secrets.BLOG_ID }}
          RSS_FEED_URL: 'https://feeds.bbci.co.uk/news/rss.xml'  # Replace if needed
        run: python rss_to_blogger.py

